// Server-side only. Never import this from client-facing <script> tags.
//
// Each provider fetches from an official, documented data source and
// normalizes its result into a single shared shape so MarketTicker.astro
// (and the API route that feeds it) never needs to know which exchange or
// vendor a quote came from.

export interface MarketQuote {
	id: string;
  	name: string;
    	shortName: string;
      	value: number | null;
        	change: number | null;
          	changePercent: number | null;
            	direction: 'up' | 'down' | 'flat';
              	updatedAt: string; // ISO 8601
                	marketStatus: 'open' | 'closed';
                  	source: string;
                    }

                    function directionOf(change: number | null): 'up' | 'down' | 'flat' {
                    	if (change === null || Number.isNaN(change)) return 'flat';
                      	if (change > 0) return 'up';
                        	if (change < 0) return 'down';
                          	return 'flat';
                            }

                            // TWSE dates come back as an ROC-calendar string, e.g. "1150917" -> 2026-09-17.
                            function rocDateToIso(roc: string): string {
                            	const digits = roc.trim();
                              	const year = parseInt(digits.slice(0, digits.length - 4), 10) + 1911;
                                	const month = digits.slice(digits.length - 4, digits.length - 2);
                                  	const day = digits.slice(digits.length - 2);
                                    	return `${year}-${month}-${day}`;
                                      }

                                      // TPEx dates come back as "115/09/17" (ROC year / month / day).
                                      function tpexDateToIso(rocSlash: string): string {
                                      	const [rocYear, month, day] = rocSlash.split('/');
                                        	const year = parseInt(rocYear, 10) + 1911;
                                          	return `${year}-${month}-${day}`;
                                            }

                                            /**
                                             * Whether it's currently within a normal TWSE/TPEx trading session
                                              * (Mon-Fri, 09:00-13:30 Asia/Taipei). Used only to pick a cache TTL —
                                               * never trust this alone to label data as "live".
                                                */
                                                export function isTaiwanMarketHours(now = new Date()): boolean {
                                                	const taipei = new Date(now.toLocaleString('en-US', { timeZone: 'Asia/Taipei' }));
                                                  	const day = taipei.getDay(); // 0 Sun ... 6 Sat
                                                    	if (day === 0 || day === 6) return false;
                                                      	const minutes = taipei.getHours() * 60 + taipei.getMinutes();
                                                        	return minutes >= 9 * 60 && minutes <= 13 * 60 + 30;
                                                          }

                                                          /** 台灣加權指數 (TAIEX) — Taiwan Stock Exchange official OpenAPI. */
                                                          export async function fetchTaiex(): Promise<MarketQuote | null> {
                                                          	try {
                                                            		const res = await fetch('https://openapi.twse.com.tw/v1/exchangeReport/MI_INDEX');
                                                                		if (!res.ok) return null;
                                                                    		const rows: Array<Record<string, string>> = await res.json();
                                                                        		const row = rows.find((r) => r['指數'] === '發行量加權股價指數');
                                                                            		if (!row) return null;

                                                                                		const value = parseFloat(row['收盤指數'].replace(/,/g, ''));
                                                                                    		const rawChange = parseFloat(row['漲跌點數'].replace(/,/g, ''));
                                                                                        		const sign = row['漲跌'] === '-' ? -1 : 1;
                                                                                            		const change = Number.isNaN(rawChange) ? null : rawChange * sign;
                                                                                                		const changePercent = parseFloat(row['漲跌百分比']);
                                                                                                    
                                                                                                    		return {
                                                                                                        			id: 'taiex',
                                                                                                              			name: '台灣加權',
                                                                                                                    			shortName: '加權',
                                                                                                                          			value: Number.isNaN(value) ? null : value,
                                                                                                                                			change,
                                                                                                                                      			changePercent: Number.isNaN(changePercent) ? null : changePercent,
                                                                                                                                            			direction: directionOf(change),
                                                                                                                                                  			updatedAt: rocDateToIso(row['日期']),
                                                                                                                                                        			marketStatus: isTaiwanMarketHours() ? 'open' : 'closed',
                                                                                                                                                              			source: 'TWSE OpenAPI',
                                                                                                                                                                    		};
                                                                                                                                                                        	} catch {
                                                                                                                                                                          		return null;
                                                                                                                                                                              	}
                                                                                                                                                                                }
                                                                                                                                                                                
                                                                                                                                                                                /** 櫃買指數 (TPEx OTC index) — Taipei Exchange's own daily-index report. */
                                                                                                                                                                                export async function fetchTpexIndex(): Promise<MarketQuote | null> {
                                                                                                                                                                                	try {
                                                                                                                                                                                  		const now = new Date();
                                                                                                                                                                                      		const taipei = new Date(now.toLocaleString('en-US', { timeZone: 'Asia/Taipei' }));
                                                                                                                                                                                          		const rocYear = taipei.getFullYear() - 1911;
                                                                                                                                                                                              		const month = String(taipei.getMonth() + 1).padStart(2, '0');
                                                                                                                                                                                                  		const dateParam = `${rocYear}/${month}`;
                                                                                                                                                                                                      
                                                                                                                                                                                                      		const url = `https://www.tpex.org.tw/web/stock/aftertrading/daily_trading_index/st41_result.php?l=zh-tw&d=${dateParam}&s=0,asc,0&o=json`;
                                                                                                                                                                                                          		const res = await fetch(url);
                                                                                                                                                                                                              		if (!res.ok) return null;
                                                                                                                                                                                                                  		const payload: any = await res.json();
                                                                                                                                                                                                                      		const table = payload?.tables?.[0];
                                                                                                                                                                                                                          		const rows: Array<[string, string, string, string, number, number]> = table?.data ?? [];
                                                                                                                                                                                                                              		if (!rows.length) return null;
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                  		// Rows are in ascending date order; the last one is the latest session.
                                                                                                                                                                                                                                      		const [dateStr, , , , indexValue, change] = rows[rows.length - 1];
                                                                                                                                                                                                                                          		const changePercent = indexValue - change !== 0 ? (change / (indexValue - change)) * 100 : null;
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                              		return {
                                                                                                                                                                                                                                                  			id: 'tpex',
                                                                                                                                                                                                                                                        			name: '櫃買',
                                                                                                                                                                                                                                                              			shortName: '櫃買',
                                                                                                                                                                                                                                                                    			value: indexValue,
                                                                                                                                                                                                                                                                          			change,
                                                                                                                                                                                                                                                                                			changePercent,
                                                                                                                                                                                                                                                                                      			direction: directionOf(change),
                                                                                                                                                                                                                                                                                            			updatedAt: tpexDateToIso(dateStr),
                                                                                                                                                                                                                                                                                                  			marketStatus: isTaiwanMarketHours() ? 'open' : 'closed',
                                                                                                                                                                                                                                                                                                        			source: 'TPEx 官方每日統計',
                                                                                                                                                                                                                                                                                                              		};
                                                                                                                                                                                                                                                                                                                  	} catch {
                                                                                                                                                                                                                                                                                                                    		return null;
                                                                                                                                                                                                                                                                                                                        	}
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                          /**
                                                                                                                                                                                                                                                                                                                           * US indices (Dow Jones, S&P 500) via Marketstack.
                                                                                                                                                                                                                                                                                                                            *
                                                                                                                                                                                                                                                                                                                             * Requires a server-only env var MARKETSTACK_API_KEY (never exposed to the
                                                                                                                                                                                                                                                                                                                              * client). Uses the "Basic" tier, which per Marketstack's plan comparison
                                                                                                                                                                                                                                                                                                                               * permits commercial use — unlike most free-tier competitors, which
                                                                                                                                                                                                                                                                                                                                * restrict free access to personal/non-commercial projects.
                                                                                                                                                                                                                                                                                                                                 *
                                                                                                                                                                                                                                                                                                                                  * NOTE: the exact symbol codes Marketstack uses for these two indices
                                                                                                                                                                                                                                                                                                                                   * (commonly "DJI.INDX" / "GSPC.INDX" in similar vendor APIs) should be
                                                                                                                                                                                                                                                                                                                                    * confirmed once a real API key is available — Marketstack's own docs are
                                                                                                                                                                                                                                                                                                                                     * the source of truth. If the request fails or the key isn't configured,
                                                                                                                                                                                                                                                                                                                                      * this returns an empty array and the ticker simply omits US markets
                                                                                                                                                                                                                                                                                                                                       * rather than breaking anything.
                                                                                                                                                                                                                                                                                                                                        */
                                                                                                                                                                                                                                                                                                                                        export async function fetchUsIndices(marketstackApiKey: string | undefined): Promise<MarketQuote[]> {
                                                                                                                                                                                                                                                                                                                                        	if (!marketstackApiKey) return [];
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                          	const symbols: Array<{ symbol: string; id: string; name: string; shortName: string }> = [
                                                                                                                                                                                                                                                                                                                                            		{ symbol: 'DJI.INDX', id: 'dowjones', name: '道瓊', shortName: '道瓊' },
                                                                                                                                                                                                                                                                                                                                                		{ symbol: 'GSPC.INDX', id: 'sp500', name: 'S&P 500', shortName: 'S&P 500' },
                                                                                                                                                                                                                                                                                                                                                    	];
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      	try {
                                                                                                                                                                                                                                                                                                                                                        		const url = `https://api.marketstack.com/v2/eod/latest?access_key=${encodeURIComponent(marketstackApiKey)}&symbols=${symbols.map((s) => s.symbol).join(',')}`;
                                                                                                                                                                                                                                                                                                                                                            		const res = await fetch(url);
                                                                                                                                                                                                                                                                                                                                                                		if (!res.ok) return [];
                                                                                                                                                                                                                                                                                                                                                                    		const payload: any = await res.json();
                                                                                                                                                                                                                                                                                                                                                                        		const data: Array<Record<string, any>> = payload?.data ?? [];
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                            		return symbols
                                                                                                                                                                                                                                                                                                                                                                                			.map((s) => {
                                                                                                                                                                                                                                                                                                                                                                                      				const row = data.find((d) => d.symbol === s.symbol);
                                                                                                                                                                                                                                                                                                                                                                                              				if (!row || typeof row.close !== 'number') return null;
                                                                                                                                                                                                                                                                                                                                                                                                      				const prevClose = typeof row.open === 'number' ? row.open : null;
                                                                                                                                                                                                                                                                                                                                                                                                              				const change = prevClose !== null ? row.close - prevClose : null;
                                                                                                                                                                                                                                                                                                                                                                                                                      				const changePercent = change !== null && prevClose ? (change / prevClose) * 100 : null;
                                                                                                                                                                                                                                                                                                                                                                                                                              				const quote: MarketQuote = {
                                                                                                                                                                                                                                                                                                                                                                                                                                      					id: s.id,
                                                                                                                                                                                                                                                                                                                                                                                                                                                					name: s.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                          					shortName: s.shortName,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    					value: row.close,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              					change,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					changePercent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  					direction: directionOf(change),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            					updatedAt: row.date ?? new Date().toISOString(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      					marketStatus: 'closed', // Marketstack Basic tier is EOD, not intraday
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                					source: 'Marketstack',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          				};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  				return quote;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          			})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                			.filter((q): q is MarketQuote => q !== null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	} catch {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		return [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            	}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              /** Fetches and normalizes all configured markets in parallel. */
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export async function fetchAllMarkets(marketstackApiKey: string | undefined): Promise<MarketQuote[]> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              	const [taiex, tpex, us] = await Promise.all([fetchTaiex(), fetchTpexIndex(), fetchUsIndices(marketstackApiKey)]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                	const quotes: MarketQuote[] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  	if (taiex) quotes.push(taiex);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    	if (tpex) quotes.push(tpex);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      	quotes.push(...us);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	return quotes;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
